MVC/Models/DataViewModel.cs
using System.Collections;
using System.Collections.Generic;

namespace MVC.Models
{
    public class DataViewModel
    {
        public List<MyData> Datas { get; set; }
        public MyData NewMyData { get; set; }
    }
}

MVC/Models/ErrorViewModel.cs
using System;

namespace MVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVC/Models/HomeViewModel.cs
using System.Collections.Generic;
using MVC.Data;

namespace MVC.Models
{
    public class HomeViewModel
    {
        public List<Subreddit> Subreddits { get; set; }
        public Subreddit NewSubreddit { get; set; }
    }
}

MVC/Models/MyData.cs
namespace MVC.Models
{
    public class MyData
    {
        public string Name { get; set; }
        public int Number { get; set; }
    }
}

MVC/Models/PostViewModel.cs
using System.Collections.Generic;
using MVC.Data;

namespace MVC.Models
{
    public class PostViewModel
    {
        public Post Post { get; set; }
        public List<Comment> Comments { get; set; }
        public Comment NewComment { get; set; }
    }
}

MVC/Models/SubredditViewModel.cs
using System.Collections.Generic;
using MVC.Data;

namespace MVC.Models
{
    public class SubredditViewModel
    {
        public Subreddit Subreddit { get; set; }
        public List<Post> Posts { get; set; }
        public Post NewPost { get; set; }
        public int SelectedId { get; set; }
    }
}

MVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MVC.Data;
using MVC.Models;

namespace MVC.Controllers
{
    public class HomeController : Controller
    {
        private DataViewModel _dataViewModel = new DataViewModel
        {
            Datas = new List<MyData>
            {
                new MyData {Name = "Agnes", Number = 1},
                new MyData {Name = "Grant", Number = 2},
                new MyData {Name = "Matt", Number = 3},
                new MyData {Name = "Sarina", Number = 4},
                new MyData {Name = "Alyssa", Number = 5},
            },
            NewMyData = new MyData()
        };

        private readonly ILogger<HomeController> _logger;
        private readonly AppDbContext _context;

        public HomeController(ILogger<HomeController> logger, AppDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public IActionResult Index()
        {
            return View(CreateVM());
        }

        public IActionResult Privacy()
        {
            return View(_dataViewModel);
        }

        public IActionResult AddData(DataViewModel model)
        {
            Console.WriteLine($"Model: {model.NewMyData.Name} - {model.NewMyData.Number}");
            if (ModelState.IsValid)
            {
                _dataViewModel.Datas.Add(model.NewMyData);
            }

            return View("Privacy", _dataViewModel);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel {RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier});
        }

        public IActionResult AddSubreddit(HomeViewModel model)
        {
            Console.WriteLine($"Name: {model.NewSubreddit.Name}");
            if (ModelState.IsValid)
            {
                _context.Add(model.NewSubreddit);
                _context.SaveChanges();
            }

            return View("Index", CreateVM());
        }

        private HomeViewModel CreateVM() => new HomeViewModel
            {Subreddits = _context.Subreddits.ToList(), NewSubreddit = new Subreddit()};
    }
}

MVC/Controllers/PostController.cs
using System.Linq;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MVC.Data;
using MVC.Models;

namespace MVC.Controllers
{
    public class PostController : Controller
    {
        private const string PostId = "PostId";
        private readonly AppDbContext _context;

        public PostController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index(int id)
        {
            HttpContext.Session.SetInt32(PostId, id);
            var vm = new PostViewModel
            {
                Post = _context.Posts.Find(id),
                Comments = _context.Comments.Where(c => c.Post.Id == id).ToList()
            };
            return View(vm);
        }

        public IActionResult AddComment(PostViewModel model)
        {
            var id = HttpContext.Session.GetInt32(PostId);
            if (!id.HasValue) return RedirectToPage("Home");

            model.NewComment.PostId = id.GetValueOrDefault();

            _context.Add(model.NewComment);
            _context.SaveChanges();

            return RedirectToAction("Index", new {id});
        }
    }
}

MVC/Controllers/SubredditController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MVC.Data;
using MVC.Models;

namespace MVC.Controllers
{
    public class SubredditController : Controller
    {
        private readonly AppDbContext _context;
        private const string SubredditId = "SubredditId";

        public SubredditController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index(int id)
        {
            try
            {
                HttpContext.Session.SetInt32(SubredditId, id);
                var vm = new SubredditViewModel
                {
                    Posts = _context.Posts.Where(p => p.Subreddit.Id == id).ToList(),
                    Subreddit = _context.Subreddits.Find(id),
                    SelectedId = id
                };
                return View(vm);
            }
            catch (ArgumentNullException e)
            {
                return RedirectToPage("Home");
            }
        }

        public IActionResult AddPost(SubredditViewModel model)
        {
            var id = HttpContext.Session.GetInt32(SubredditId);

            if (!id.HasValue) return RedirectToPage("Home");

            if (!ModelState.IsValid) return RedirectToAction("Index", new {id});
            model.NewPost.SubredditId = id.GetValueOrDefault();
            _context.Add(model.NewPost);
            _context.SaveChanges();

            return RedirectToAction("Index", new {id});
        }
    }
}

MVC/ViewComponents/TextBoxViewComponent.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MVC.Models;

namespace MVC.ViewComponents
{
    public class TextBoxViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(string name, int number)
        {
            var n = await Task.FromResult(name);
            return View(new MyData {Name = n, Number = number});
        }   
    }
}

MVC/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Mvc.Rendering
@model HomeViewModel
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1>Welcome</h1>
    <h2>Subreddits</h2>
    <ul class="list">
        @foreach (var sr in Model.Subreddits)
        {
            <li>
                @Html.ActionLink(
                    sr.Name,
                    "Index",
                    "Subreddit",
                    new {sr.Id})
            </li>
        }
    </ul>
    @using (Html.BeginForm("AddSubreddit", "Home", FormMethod.Post))
    {
        <div>
            <div>
                @Html.LabelFor(model => model.NewSubreddit.Name)
                @Html.TextBoxFor(model => model.NewSubreddit.Name)
                @Html.ValidationMessage("Name")
            </div>
            <input type="submit" value="Submit"/>
        </div>
    }
</div>

MVC/Views/Post/Index.cshtml
@model PostViewModel
<h2>@Model.Post.Name</h2>
<p>@Model.Post.Text</p>
<h3>Add Comment</h3>
@using (Html.BeginForm("AddComment", "Post", FormMethod.Post))
{
    <div>
        <div >
            @Html.LabelFor(model => model.NewComment.Text)
            @Html.TextAreaFor(model => model.NewComment.Text)
            @Html.ValidationMessage("NewComment")
        </div>
        <input type="submit" value="Submit"/>
    </div>
}

<h3>Comments</h3>
<ul>
    @foreach (var comment in Model.Comments)
    {
        <li>
            <p><span>@comment.Score</span> | @comment.Text</p>
        </li>
    }
</ul>

MVC/Views/Shared/Components/TextBox/Default.cshtml
@model MyData
<h1>@Model.Name</h1>

MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Fake Reddit</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/clarity.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<div class="main-container">
    <header class="header header-6">
        <div class="branding">
            <a class="title" asp-area="" asp-controller="Home" asp-action="Index">MVC</a>
        </div>
        @* <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent" *@
        @*         aria-expanded="false" aria-label="Toggle navigation"> *@
        @*     <span class="navbar-toggler-icon"></span> *@
        @* </button> *@
        <div class="divider"></div>
        <div class="header-nav">
            <a class="nav-link @(ViewContext.RouteData.Values["Controller"].ToString() == "Home" ? "active" : "")" asp-area="" asp-controller="Home" asp-action="Index">Subreddits</a>
        </div>
    </header>
    <div class="content-container">
        <div class="content-area">
            @RenderBody()
        </div>
    </div>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2020 - MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("Scripts", required: false)
</body>
</html>

MVC/Views/Subreddit/Index.cshtml
@model SubredditViewModel

<h2>@Model.Subreddit.Name</h2>
<h3>Posts</h3>
<ul>
    @foreach (var post in Model.Posts)
    {
        <li>@Html.ActionLink(post.Name, "Index", "Post", new {post.Id})</li>
    }
</ul>

<h3>Add Post</h3>
@using (Html.BeginForm("AddPost", "Subreddit", FormMethod.Post,
    new {@class = "clr-form clr-form-horizontal", @style = "display: flex; flex-direction: column;"}))
{
    <div class="clr-form-control">
        @Html.LabelFor(model => model.NewPost.Name, new {@class = "clr-control-label", @style = "width: 3rem;"})
        <div class="clr-control-container">
            @Html.TextBoxFor(model => model.NewPost.Name, new {@class = "clr-input"})
        </div>
        @Html.ValidationMessage("Name")
    </div>
    <div class="clr-form-control">
        @Html.LabelFor(model => model.NewPost.Text, new {@class = "clr-control-label", @style = "width: 3rem;"})
        @Html.TextBoxFor(model => model.NewPost.Text, new {@class = "clr-input"})
        @Html.ValidationMessage("Text")
    </div>
    <input type="submit" value="Submit" class="btn btn-primary"/>
}

<vc:text-box name="hello" number="2"></vc:text-box>